package com.hbm.tileentity;

import com.hbm.tileentity.bomb.*;
import com.hbm.tileentity.conductor.*;
import com.hbm.tileentity.deco.*;
import com.hbm.tileentity.machine.*;
import com.hbm.tileentity.machine.rbmk.*;
import com.hbm.tileentity.turret.*;
import cpw.mods.fml.common.registry.GameRegistry;

public class HBMTileEntity {
	
	public static void preInitialization() {
		
		GameRegistry.registerTileEntity(TileEntityTestBombAdvanced.class, "tilentity_testbombadvanced");
		GameRegistry.registerTileEntity(TileEntityDiFurnace.class, "tilentity_diFurnace");
		GameRegistry.registerTileEntity(TileEntityTestNuke.class, "tilentity_testnuke");
		GameRegistry.registerTileEntity(TileEntityRotationTester.class, "tilentity_rotationtester");
		GameRegistry.registerTileEntity(TileEntityTestRender.class, "tilentity_testrenderer");
		GameRegistry.registerTileEntity(TileEntityTestContainer.class, "tilentity_testcontainer");
		GameRegistry.registerTileEntity(TileEntityObjTester.class, "tilentity_objtester");
		GameRegistry.registerTileEntity(TileEntityNukeGadget.class, "tilentity_nukegadget");
		GameRegistry.registerTileEntity(TileEntityNukeBoy.class, "tilentity_nukeboy");
		GameRegistry.registerTileEntity(TileEntityMachineCentrifuge.class, "tileentity_centrifuge");
		GameRegistry.registerTileEntity(TileEntityNukeMan.class, "tileentity_nukeman");
		GameRegistry.registerTileEntity(TileEntityMachineUF6Tank.class, "tileentity_uf6_tank");
		GameRegistry.registerTileEntity(TileEntityMachinePuF6Tank.class, "tileentity_puf6_tank");
		GameRegistry.registerTileEntity(TileEntityMachineReactor.class, "tileentity_reactor");
		GameRegistry.registerTileEntity(TileEntityBombMulti.class, "tileentity_bombmulti");
		GameRegistry.registerTileEntity(TileEntityNukeMike.class, "tileentity_nukemike");
		GameRegistry.registerTileEntity(TileEntityNukeTsar.class, "tileentity_nuketsar");
		GameRegistry.registerTileEntity(TileEntityNukeFurnace.class, "tileentity_nukefurnace");
		GameRegistry.registerTileEntity(TileEntityRtgFurnace.class, "tileentity_rtgfurnace");
		GameRegistry.registerTileEntity(TileEntityMachineGenerator.class, "tileentity_generator");
		GameRegistry.registerTileEntity(TileEntityMachineElectricFurnace.class, "tileentity_electric_furnace");
		GameRegistry.registerTileEntity(TileEntityNukeFleija.class, "tileentity_nukefleija");
		GameRegistry.registerTileEntity(TileEntityDecoTapeRecorder.class, "tileentity_taperecorder");
		GameRegistry.registerTileEntity(TileEntityDecoSteelPoles.class, "tileentity_steelpoles");
		GameRegistry.registerTileEntity(TileEntityDecoPoleTop.class, "tileentity_poletop");
		GameRegistry.registerTileEntity(TileEntityDecoPoleSatelliteReceiver.class, "tileentity_satellitereceicer");
		GameRegistry.registerTileEntity(TileEntityMachineDeuterium.class, "tileentity_deuterium");
		GameRegistry.registerTileEntity(TileEntityWireCoated.class, "tileentity_wirecoated");
		GameRegistry.registerTileEntity(TileEntityMachineBattery.class, "tileentity_battery");
		GameRegistry.registerTileEntity(TileEntityMachineCoal.class, "tileentity_coal");
		GameRegistry.registerTileEntity(TileEntityNukePrototype.class, "tileentity_nukeproto");
		GameRegistry.registerTileEntity(TileEntityRedBarrel.class, "tileentity_barrel");
		GameRegistry.registerTileEntity(TileEntityYellowBarrel.class, "tileentity_nukebarrel");
		GameRegistry.registerTileEntity(TileEntityLaunchPad.class, "tileentity_launch1");
		GameRegistry.registerTileEntity(TileEntityDecoBlock.class, "tileentity_deco");
		GameRegistry.registerTileEntity(TileEntityDecoBlockAltW.class, "tileentity_deco_w");
		GameRegistry.registerTileEntity(TileEntityDecoBlockAltG.class, "tileentity_deco_g");
		GameRegistry.registerTileEntity(TileEntityDecoBlockAltF.class, "tileentity_deco_f");
		GameRegistry.registerTileEntity(TileEntityCoreTitanium.class, "tileentity_core_titanium");
		GameRegistry.registerTileEntity(TileEntityCoreAdvanced.class, "tileentity_core_advanced");
		GameRegistry.registerTileEntity(TileEntityFusionMultiblock.class, "tileentity_fusion_multiblock");
		GameRegistry.registerTileEntity(TileEntityCrashedBomb.class, "tileentity_crashed_balefire");
		GameRegistry.registerTileEntity(TileEntityCable.class, "tileentity_cable");
		GameRegistry.registerTileEntity(TileEntityConverterHeRf.class, "tileentity_converter_herf");
		GameRegistry.registerTileEntity(TileEntityConverterRfHe.class, "tileentity_converter_rfhe");
		GameRegistry.registerTileEntity(TileEntityMachineSchrabidiumTransmutator.class, "tileentity_schrabidium_transmutator");
		GameRegistry.registerTileEntity(TileEntityMachineDiesel.class, "tileentity_diesel_generator");
		GameRegistry.registerTileEntity(TileEntityWatzCore.class, "tileentity_watz_multiblock");
		GameRegistry.registerTileEntity(TileEntityMachineShredder.class, "tileentity_machine_shredder");
		GameRegistry.registerTileEntity(TileEntityMachineCMBFactory.class, "tileentity_machine_cmb");
		GameRegistry.registerTileEntity(TileEntityFWatzCore.class, "tileentity_fwatz_multiblock");
		GameRegistry.registerTileEntity(TileEntityMachineTeleporter.class, "tileentity_teleblock");
		GameRegistry.registerTileEntity(TileEntityNukeCustom.class, "tileentity_nuke_custom");
		GameRegistry.registerTileEntity(TileEntityHatch.class, "tileentity_seal_lid");
		GameRegistry.registerTileEntity(TileEntityMachineIGenerator.class, "tileentity_igenerator");
		GameRegistry.registerTileEntity(TileEntityDummy.class, "tileentity_dummy");
		GameRegistry.registerTileEntity(TileEntityMachineCyclotron.class, "tileentity_cyclotron");
		GameRegistry.registerTileEntity(TileEntityMachineOilWell.class, "tileentity_derrick");
		GameRegistry.registerTileEntity(TileEntityMachineGasFlare.class, "tileentity_gasflare");
		GameRegistry.registerTileEntity(TileEntityMachineRefinery.class, "tileentity_refinery");
		GameRegistry.registerTileEntity(TileEntityOilDuct.class, "tileentity_oil_duct");
		GameRegistry.registerTileEntity(TileEntityOilDuctSolid.class, "tileentity_oil_duct_solid");
		GameRegistry.registerTileEntity(TileEntityGasDuct.class, "tileentity_gas_duct");
		GameRegistry.registerTileEntity(TileEntityGasDuctSolid.class, "tileentity_gas_duct_solid");
		GameRegistry.registerTileEntity(TileEntityMachineRTG.class, "tileentity_machine_rtg");
		GameRegistry.registerTileEntity(TileEntityPylonRedWire.class, "tileentity_pylon_redwire");
		GameRegistry.registerTileEntity(TileEntityStructureMarker.class, "tileentity_structure_marker");
		GameRegistry.registerTileEntity(TileEntityMachineMiningDrill.class, "tileentity_mining_drill");
		GameRegistry.registerTileEntity(TileEntityMachineAssembler.class, "tileentity_assembly_machine");
		GameRegistry.registerTileEntity(TileEntityFluidDuct.class, "tileentity_universal_duct");
		GameRegistry.registerTileEntity(TileEntityMachineChemplant.class, "tileentity_chemical_plant");
		GameRegistry.registerTileEntity(TileEntityMachineFluidTank.class, "tileentity_fluid_tank");
		GameRegistry.registerTileEntity(TileEntityTurretHeavy.class, "tileentity_turret_heavy");
		GameRegistry.registerTileEntity(TileEntityTurretRocket.class, "tileentity_turret_rocket");
		GameRegistry.registerTileEntity(TileEntityTurretLight.class, "tileentity_turret_light");
		GameRegistry.registerTileEntity(TileEntityTurretFlamer.class, "tileentity_turret_flamer");
		GameRegistry.registerTileEntity(TileEntityTurretTau.class, "tileentity_turret_tau");
		GameRegistry.registerTileEntity(TileEntityMachinePumpjack.class, "tileentity_machine_pumpjack");
		GameRegistry.registerTileEntity(TileEntityMachineTurbofan.class, "tileentity_machine_turbofan");
		GameRegistry.registerTileEntity(TileEntityCrateIron.class, "tileentity_crate_iron");
		GameRegistry.registerTileEntity(TileEntityCrateSteel.class, "tileentity_crate_steel");
		GameRegistry.registerTileEntity(TileEntityMachinePress.class, "tileentity_press");
		GameRegistry.registerTileEntity(TileEntityAMSBase.class, "tileentity_ams_base");
		GameRegistry.registerTileEntity(TileEntityAMSEmitter.class, "tileentity_ams_emitter");
		GameRegistry.registerTileEntity(TileEntityAMSLimiter.class, "tileentity_ams_limiter");
		GameRegistry.registerTileEntity(TileEntityMachineSiren.class, "tileentity_siren");
		GameRegistry.registerTileEntity(TileEntityMachineSPP.class, "tileentity_spp");
		GameRegistry.registerTileEntity(TileEntityTurretSpitfire.class, "tileentity_turret_spitfire");
		GameRegistry.registerTileEntity(TileEntityMachineRadGen.class, "tileentity_radgen");
		GameRegistry.registerTileEntity(TileEntityMachineTransformer.class, "tileentity_transformer");
		GameRegistry.registerTileEntity(TileEntityTurretCIWS.class, "tileentity_turret_cwis");
		GameRegistry.registerTileEntity(TileEntityMachineRadar.class, "tileentity_radar");
		GameRegistry.registerTileEntity(TileEntityBroadcaster.class, "tileentity_pink_cloud_broadcaster");
		GameRegistry.registerTileEntity(TileEntityTurretCheapo.class, "tileentity_turret_cheapo");
		GameRegistry.registerTileEntity(TileEntityNukeSolinium.class, "tileentity_nuke_solinium");
		GameRegistry.registerTileEntity(TileEntityNukeN2.class, "tileentity_nuke_n2");
		GameRegistry.registerTileEntity(TileEntityCelPrime.class, "tileentity_cel_prime");
		GameRegistry.registerTileEntity(TileEntityCelPrimeTerminal.class, "tileentity_cel_prime_access");
		GameRegistry.registerTileEntity(TileEntityCelPrimeBattery.class, "tileentity_cel_prime_energy");
		GameRegistry.registerTileEntity(TileEntityCelPrimePort.class, "tileentity_cel_prime_connector");
		GameRegistry.registerTileEntity(TileEntityCelPrimeTanks.class, "tileentity_cel_prime_storage");
		GameRegistry.registerTileEntity(TileEntityMachineSeleniumEngine.class, "tileentity_selenium_engine");
		GameRegistry.registerTileEntity(TileEntityMachineSatLinker.class, "tileentity_satlinker");
		GameRegistry.registerTileEntity(TileEntityMachineReactorSmall.class, "tileentity_small_reactor");
		GameRegistry.registerTileEntity(TileEntityVaultDoor.class, "tileentity_vault_door");
		GameRegistry.registerTileEntity(TileEntityRadiobox.class, "tileentity_radio_broadcaster");
		GameRegistry.registerTileEntity(TileEntityRadioRec.class, "tileentity_radio_receiver");
		GameRegistry.registerTileEntity(TileEntityVent.class, "tileentity_vent");
		GameRegistry.registerTileEntity(TileEntityLandmine.class, "tileentity_landmine");
		GameRegistry.registerTileEntity(TileEntityBomber.class, "tileentity_bomber");
		GameRegistry.registerTileEntity(TileEntityMachineTeleLinker.class, "tileentity_telemetry_linker");
		GameRegistry.registerTileEntity(TileEntityMachineKeyForge.class, "tileentity_key_forge");
		GameRegistry.registerTileEntity(TileEntitySellafield.class, "tileentity_sellafield_core");
		GameRegistry.registerTileEntity(TileEntityNukeN45.class, "tileentity_n45");
		GameRegistry.registerTileEntity(TileEntityBlastDoor.class, "tileentity_blast_door");
		GameRegistry.registerTileEntity(TileEntitySafe.class, "tileentity_safe");
		GameRegistry.registerTileEntity(TileEntityMachineGasCent.class, "tileentity_gas_centrifuge");
		GameRegistry.registerTileEntity(TileEntityMachineBoiler.class, "tileentity_boiler");
		GameRegistry.registerTileEntity(TileEntityMachineBoilerElectric.class, "tileentity_electric_boiler");
		GameRegistry.registerTileEntity(TileEntityMachineTurbine.class, "tileentity_turbine");
		GameRegistry.registerTileEntity(TileEntityGeiger.class, "tileentity_geiger");
		GameRegistry.registerTileEntity(TileEntityFF.class, "tileentity_forcefield");
		GameRegistry.registerTileEntity(TileEntityForceField.class, "tileentity_machine_field");
		GameRegistry.registerTileEntity(TileEntityMachineShredderLarge.class, "tileentity_machine_big_shredder");
		GameRegistry.registerTileEntity(TileEntityRFDuct.class, "tileentity_hbm_rfduct");
		GameRegistry.registerTileEntity(TileEntityReactorControl.class, "tileentity_reactor_remote_control");
		GameRegistry.registerTileEntity(TileEntityMachineReactorLarge.class, "tileentity_large_reactor");
		GameRegistry.registerTileEntity(TileEntityWasteDrum.class, "tileentity_waste_drum");
		GameRegistry.registerTileEntity(TileEntityDecon.class, "tileentity_decon");
		GameRegistry.registerTileEntity(TileEntityMachineSatDock.class, "tileentity_miner_dock");
		GameRegistry.registerTileEntity(TileEntityMachineEPress.class, "tileentity_electric_press");
		GameRegistry.registerTileEntity(TileEntityCoreEmitter.class, "tileentity_v0_emitter");
		GameRegistry.registerTileEntity(TileEntityCoreReceiver.class, "tileentity_v0_receiver");
		GameRegistry.registerTileEntity(TileEntityCoreInjector.class, "tileentity_v0_injector");
		GameRegistry.registerTileEntity(TileEntityCoreStabilizer.class, "tileentity_v0_stabilizer");
		GameRegistry.registerTileEntity(TileEntityCore.class, "tileentity_v0");
		GameRegistry.registerTileEntity(TileEntityMachineArcFurnace.class, "tileentity_arc_furnace");
		GameRegistry.registerTileEntity(TileEntityMachineAmgen.class, "tileentity_amgen");
		GameRegistry.registerTileEntity(TileEntityGeysir.class, "tileentity_geysir");
		GameRegistry.registerTileEntity(TileEntityMachineMissileAssembly.class, "tileentity_missile_assembly");
		GameRegistry.registerTileEntity(TileEntityLaunchTable.class, "tileentity_large_launch_table");
		GameRegistry.registerTileEntity(TileEntityCompactLauncher.class, "tileentity_small_launcher");
		GameRegistry.registerTileEntity(TileEntityMultiblock.class, "tileentity_multi_core");
		GameRegistry.registerTileEntity(TileEntityChlorineSeal.class, "tileentity_chlorine_seal");
		GameRegistry.registerTileEntity(TileEntityCableSwitch.class, "tileentity_he_switch");
		GameRegistry.registerTileEntity(TileEntitySoyuzLauncher.class, "tileentity_soyuz_launcher");
		GameRegistry.registerTileEntity(TileEntityTesla.class, "tileentity_tesla_coil");
		GameRegistry.registerTileEntity(TileEntityBarrel.class, "tileentity_fluid_barrel");
		GameRegistry.registerTileEntity(TileEntityCyberCrab.class, "tileentity_crabs");
		GameRegistry.registerTileEntity(TileEntitySoyuzCapsule.class, "tileentity_soyuz_capsule");
		GameRegistry.registerTileEntity(TileEntityMachineCrystallizer.class, "tileentity_acidomatic");
		GameRegistry.registerTileEntity(TileEntitySoyuzStruct.class, "tileentity_soyuz_struct");
		GameRegistry.registerTileEntity(TileEntityITERStruct.class, "tileentity_iter_struct");
		GameRegistry.registerTileEntity(TileEntityMachineMiningLaser.class, "tileentity_mining_laser");
		GameRegistry.registerTileEntity(TileEntityProxyInventory.class, "tileentity_proxy_inventory");
		GameRegistry.registerTileEntity(TileEntityProxyEnergy.class, "tileentity_proxy_power");
		GameRegistry.registerTileEntity(TileEntityNukeBalefire.class, "tileentity_nuke_fstbmb");
		GameRegistry.registerTileEntity(TileEntityProxyCombo.class, "tileentity_proxy_combo");
		GameRegistry.registerTileEntity(TileEntityMicrowave.class, "tileentity_microwave");
		GameRegistry.registerTileEntity(TileEntityMachineMiniRTG.class, "tileentity_mini_rtg");
		GameRegistry.registerTileEntity(TileEntityITER.class, "tileentity_iter");
		GameRegistry.registerTileEntity(TileEntityMachinePlasmaHeater.class, "tileentity_plasma_heater");
		GameRegistry.registerTileEntity(TileEntityMachineFENSU.class, "tileentity_fensu");
		GameRegistry.registerTileEntity(TileEntityTrappedBrick.class, "tileentity_trapped_brick");
		GameRegistry.registerTileEntity(TileEntityPlasmaStruct.class, "tileentity_plasma_struct");
		GameRegistry.registerTileEntity(TileEntityMachineLargeTurbine.class, "tileentity_industrial_turbine");
		GameRegistry.registerTileEntity(TileEntityHadronDiode.class, "tileentity_hadron_diode");
		GameRegistry.registerTileEntity(TileEntityHadronPower.class, "tileentity_hadron_power");
		GameRegistry.registerTileEntity(TileEntityHadron.class, "tileentity_hadron");
		GameRegistry.registerTileEntity(TileEntitySolarBoiler.class, "tileentity_solarboiler");
		GameRegistry.registerTileEntity(TileEntitySolarMirror.class, "tileentity_solarmirror");
		GameRegistry.registerTileEntity(TileEntityMachineDetector.class, "tileentity_he_detector");
		GameRegistry.registerTileEntity(TileEntityFireworks.class, "tileentity_firework_box");
		GameRegistry.registerTileEntity(TileEntityCrateTungsten.class, "tileentity_crate_hot");
		GameRegistry.registerTileEntity(TileEntityTurretChekhov.class, "tileentity_turret_chekhov");
		GameRegistry.registerTileEntity(TileEntityTurretJeremy.class, "tileentity_turret_jeremy");
		GameRegistry.registerTileEntity(TileEntityTurretTauon.class, "tileentity_turret_tauon");
		GameRegistry.registerTileEntity(TileEntityTurretFriendly.class, "tileentity_turret_friendly");
		GameRegistry.registerTileEntity(TileEntityTurretRichard.class, "tileentity_turret_richard");
		GameRegistry.registerTileEntity(TileEntityTurretHoward.class, "tileentity_turret_howard");
		GameRegistry.registerTileEntity(TileEntitySILEX.class, "tileentity_silex");
		GameRegistry.registerTileEntity(TileEntityFEL.class, "tileentity_fel");

		GameRegistry.registerTileEntity(TileEntityRBMKRod.class, "tileentity_rbmk_rod");
		GameRegistry.registerTileEntity(TileEntityRBMKControl.class, "tileentity_rbmk_control");
		GameRegistry.registerTileEntity(TileEntityRBMKBlank.class, "tileentity_rbmk_blank");
		GameRegistry.registerTileEntity(TileEntityRBMKBoiler.class, "tileentity_rbmk_boiler");
		GameRegistry.registerTileEntity(TileEntityRBMKReflector.class, "tileentity_rbmk_reflector");
		GameRegistry.registerTileEntity(TileEntityRBMKAbsorber.class, "tileentity_rbmk_absorber");
		GameRegistry.registerTileEntity(TileEntityRBMKModerator.class, "tileentity_rbmk_moderator");
		GameRegistry.registerTileEntity(TileEntityRBMKConsole.class, "tileentity_rbmk_console");
	}
	
	public static void Initialization() {}
	
	public static void postInitialization() {}


	
	/*
	public static void preInitialization();
	
	public static void Initialization();
	
	public static void postInitialization()
	*/
}
