package com.hbm.entity;

import com.hbm.entity.effect.*;
import com.hbm.entity.grenade.*;
import com.hbm.entity.item.*;
import com.hbm.entity.logic.*;
import com.hbm.entity.missile.*;
import com.hbm.entity.mob.*;
import com.hbm.entity.mob.botprime.*;
import com.hbm.entity.particle.*;
import com.hbm.entity.projectile.*;
import com.hbm.main.MainRegistry;

import cpw.mods.fml.common.registry.EntityRegistry;

public class HBMEntity {

	public static void preInitialization() {
		EntityRegistry.registerModEntity(EntityRocket.class, "entity_rocket", 0, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityNukeExplosion.class, "entity_nuke_explosion", 1, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityNukeExplosionAdvanced.class, "entity_nuke_explosion_advanced", 2, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeGeneric.class, "entity_grenade_generic", 3, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeStrong.class, "entity_grenade_strong", 4, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeFrag.class, "entity_grenade_frag", 5, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeFire.class, "entity_grenade_fire", 6, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeCluster.class, "entity_grenade_cluster", 7, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityTestMissile.class, "entity_test_missile", 8, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityNukeCloudSmall.class, "entity_nuke_cloud_small", 9, MainRegistry.instance, 10000, 1, true);
		EntityRegistry.registerModEntity(EntityBullet.class, "entity_bullet", 10, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeFlare.class, "entity_grenade_flare", 11, MainRegistry.instance, 500, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeElectric.class, "entity_grenade_electric", 12, MainRegistry.instance, 500, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadePoison.class, "entity_grenade_poison", 13, MainRegistry.instance, 500, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeGas.class, "entity_grenade_gas", 14, MainRegistry.instance, 500, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeSchrabidium.class, "entity_grenade_schrab", 15, MainRegistry.instance, 500, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeNuke.class, "entity_grenade_nuke", 16, MainRegistry.instance, 500, 1, true);
		EntityRegistry.registerModEntity(EntitySchrab.class, "entity_schrabnel", 17, MainRegistry.instance, 500, 1, true);
		EntityRegistry.registerModEntity(EntityMissileGeneric.class, "entity_missile_generic", 18, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMissileStrong.class, "entity_missile_strong", 19, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMissileNuclear.class, "entity_missile_nuclear", 20, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMissileCluster.class, "entity_missile_cluster", 21, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMissileIncendiary.class, "entity_missile_incendiary", 22, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMissileAntiBallistic.class, "entity_missile_anti", 23, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMissileBunkerBuster.class, "entity_missile_buster", 24, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMissileIncendiaryStrong.class, "entity_missile_incendiary_strong", 25, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMissileClusterStrong.class, "entity_missile_cluster_strong", 26, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMissileBusterStrong.class, "entity_missile_buster_strong", 27, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMissileBurst.class, "entity_missile_burst", 28, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMissileInferno.class, "entity_missile_inferno", 29, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMissileRain.class, "entity_missile_rain", 30, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMissileDrill.class, "entity_missile_drill", 31, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMissileEndo.class, "entity_missile_endo", 32, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMissileExo.class, "entity_missile_exo", 33, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMissileMirv.class, "entity_missile_mirv", 34, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMIRV.class, "entity_mirvlet", 35, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntitySmokeFX.class, "entity_smoke_fx", 37, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityNukeCloudBig.class, "entity_nuke_cloud_big", 38, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeNuclear.class, "entity_grenade_nuclear", 39, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityBSmokeFX.class, "entity_b_smoke_fx", 40, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadePlasma.class, "entity_grenade_plasma", 41, MainRegistry.instance, 500, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeTau.class, "entity_grenade_tau", 42, MainRegistry.instance, 500, 1, true);
		EntityRegistry.registerModEntity(EntityChopperMine.class, "entity_chopper_mine", 43, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityCombineBall.class, "entity_combine_ball", 44, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityRainbow.class, "entity_rainbow", 45, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeLemon.class, "entity_grenade_lemon", 46, MainRegistry.instance, 500, 1, true);
		EntityRegistry.registerModEntity(EntityCloudFleija.class, "entity_cloud_fleija", 47, MainRegistry.instance, 500, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeMk2.class, "entity_grenade_mk2", 48, MainRegistry.instance, 500, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeZOMG.class, "entity_grenade_zomg", 49, MainRegistry.instance, 500, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeASchrab.class, "entity_grenade_aschrab", 50, MainRegistry.instance, 500, 1, true);
		EntityRegistry.registerModEntity(EntityNukeCloudNoShroom.class, "entity_nuke_cloud_no", 51, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityFalloutRain.class, "entity_fallout", 52, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityDischarge.class, "entity_emp_discharge", 53, MainRegistry.instance, 500, 1, true);
		EntityRegistry.registerModEntity(EntityEMPBlast.class, "entity_emp_blast", 54, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityFire.class, "entity_fire", 57, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityPlasmaBeam.class, "entity_immolator_beam", 58, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityLN2.class, "entity_LN2", 59, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityNightmareBlast.class, "entity_ominous_bullet", 60, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadePulse.class, "entity_grenade_pulse", 61, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityNukeExplosionPlus.class, "entity_nuke_explosion_advanced", 62, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityLaserBeam.class, "entity_laser_beam", 63, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMinerBeam.class, "entity_miner_beam", 64, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityRubble.class, "entity_rubble", 65, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityDSmokeFX.class, "entity_d_smoke_fx", 66, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntitySSmokeFX.class, "entity_s_smoke_fx", 67, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityShrapnel.class, "entity_shrapnel", 68, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeShrapnel.class, "entity_grenade_shrapnel", 69, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityBlackHole.class, "entity_black_hole", 70, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeBlackHole.class, "entity_grenade_black_hole", 71, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityOilSpillFX.class, "entity_spill_fx", 72, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityOilSpill.class, "entity_oil_spill", 73, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityGasFX.class, "entity_spill_fx", 74, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityGasFlameFX.class, "entity_gasflame_fx", 75, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMinecartTest.class, "entity_minecart_test", 76, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntitySparkBeam.class, "entity_spark_beam", 77, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMissileDoomsday.class, "entity_missile_doomsday", 78, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityBombletTheta.class, "entity_theta", 79, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityBombletSelena.class, "entity_selena", 80, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityTSmokeFX.class, "entity_t_smoke_fx", 81, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityNukeExplosionMK3.class, "entity_nuke_mk3", 82, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityVortex.class, "entity_vortex", 83, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityMeteor.class, "entity_meteor", 84, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityLaser.class, "entity_laser", 85, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityBoxcar.class, "entity_boxcar", 86, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMissileTaint.class, "entity_missile_taint", 87, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeGascan.class, "entity_grenade_gascan", 88, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityNukeExplosionMK4.class, "entity_nuke_mk4", 89, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityCloudFleijaRainbow.class, "entity_cloud_rainbow", 90, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityExplosiveBeam.class, "entity_beam_bomb", 91, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityAAShell.class, "entity_aa_shell", 92, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityRocketHoming.class, "entity_stinger", 93, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMissileMicro.class, "entity_missile_micronuclear", 94, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityCloudSolinium.class, "entity_cloud_rainbow", 95, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityRagingVortex.class, "entity_raging_vortex", 96, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityCarrier.class, "entity_missile_carrier", 97, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityBooster.class, "entity_missile_booster", 98, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityModBeam.class, "entity_beam_bang", 99, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMissileBHole.class, "entity_missile_blackhole", 100, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMissileSchrabidium.class, "entity_missile_schrabidium", 101, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMissileEMP.class, "entity_missile_emp", 102, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityChlorineFX.class, "entity_chlorine_fx", 103, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityPinkCloudFX.class, "entity_pink_cloud_fx", 104, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityCloudFX.class, "entity_cloud_fx", 105, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadePC.class, "entity_grenade_pink_cloud", 106, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeCloud.class, "entity_grenade_cloud", 107, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityBomber.class, "entity_bomber", 108, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityBombletZeta.class, "entity_zeta", 109, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityOrangeFX.class, "entity_agent_orange", 110, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityDeathBlast.class, "entity_laser_blast", 111, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeSmart.class, "entity_grenade_smart", 112, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeMIRV.class, "entity_grenade_mirv", 113, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeBreach.class, "entity_grenade_breach", 114, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeBurst.class, "entity_grenade_burst", 115, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityBurningFOEQ.class, "entity_burning_foeq", 116, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeIFGeneric.class, "entity_grenade_ironshod", 117, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeIFHE.class, "entity_grenade_ironshod", 118, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeIFBouncy.class, "entity_grenade_ironshod", 119, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeIFSticky.class, "entity_grenade_ironshod", 120, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeIFImpact.class, "entity_grenade_ironshod", 121, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeIFIncendiary.class, "entity_grenade_ironshod", 122, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeIFToxic.class, "entity_grenade_ironshod", 123, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeIFConcussion.class, "entity_grenade_ironshod", 124, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeIFBrimstone.class, "entity_grenade_ironshod", 125, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeIFMystery.class, "entity_grenade_ironshod", 126, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeIFSpark.class, "entity_grenade_ironshod", 127, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeIFHopwire.class, "entity_grenade_ironshod", 128, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityGrenadeIFNull.class, "entity_grenade_ironshod", 129, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityFallingNuke.class, "entity_falling_bomb", 130, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityBulletBase.class, "entity_bullet_mk2", 131, MainRegistry.instance, 250, 1, true);
		EntityRegistry.registerModEntity(EntityMinerRocket.class, "entity_miner_lander", 132, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityFogFX.class, "entity_nuclear_fog", 133, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityDuchessGambit.class, "entity_duchessgambit", 134, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMissileEMPStrong.class, "entity_missile_emp_strong", 135, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityEMP.class, "entity_emp_logic", 136, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityWaterSplash.class, "entity_water_splash", 137, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityBobmazon.class, "entity_bobmazon_delivery", 138, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMissileCustom.class, "entity_custom_missile", 139, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityBalefire.class, "entity_balefire", 140, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityTom.class, "entity_tom_the_moonstone", 141, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityTomBlast.class, "entity_tom_bust", 142, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityBuilding.class, "entity_falling_building", 143, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntitySoyuz.class, "entity_soyuz", 144, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntitySoyuzCapsule.class, "entity_soyuz_capsule", 145, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityMovingItem.class, "entity_c_item", 146, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityCloudTom.class, "entity_moonstone_blast", 147, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityBeamVortex.class, "entity_vortex_beam", 148, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityFireworks.class, "entity_firework_ball", 149, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityWastePearl.class, "entity_waste_pearl", 150, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityBOTPrimeHead.class, "entity_balls_o_tron", 151, MainRegistry.instance, 1000, 1, true);
		EntityRegistry.registerModEntity(EntityBOTPrimeBody.class, "entity_balls_o_tron_seg", 152, MainRegistry.instance, 1000, 1, true);

		EntityRegistry.registerGlobalEntityID(EntityNuclearCreeper.class, "entity_mob_nuclear_creeper", EntityRegistry.findGlobalUniqueEntityId(), 0x204131, 0x75CE00);
		EntityRegistry.registerGlobalEntityID(EntityTaintedCreeper.class, "entity_mob_tainted_creeper", EntityRegistry.findGlobalUniqueEntityId(), 0x813b9b, 0xd71fdd);
		EntityRegistry.registerGlobalEntityID(EntityHunterChopper.class, "entity_mob_hunter_chopper", EntityRegistry.findGlobalUniqueEntityId(), 0x000020, 0x2D2D72);
		EntityRegistry.registerGlobalEntityID(EntityCyberCrab.class, "entity_cyber_crab", EntityRegistry.findGlobalUniqueEntityId(), 0xAAAAAA, 0x444444);
		EntityRegistry.registerGlobalEntityID(EntityTeslaCrab.class, "entity_tesla_crab", EntityRegistry.findGlobalUniqueEntityId(), 0xAAAAAA, 0x440000);
		EntityRegistry.registerGlobalEntityID(EntityTaintCrab.class, "entity_taint_crab", EntityRegistry.findGlobalUniqueEntityId(), 0xAAAAAA, 0xFF00FF);
		EntityRegistry.registerGlobalEntityID(EntityMaskMan.class, "entity_mob_mask_man", EntityRegistry.findGlobalUniqueEntityId(), 0x818572, 0xC7C1B7);
		EntityRegistry.registerGlobalEntityID(EntityDuck.class, "entity_fucc_a_ducc", EntityRegistry.findGlobalUniqueEntityId(), 0xd0d0d0, 0xFFBF00);
		EntityRegistry.registerGlobalEntityID(EntityQuackos.class, "entity_elder_one", EntityRegistry.findGlobalUniqueEntityId(), 0xd0d0d0, 0xFFBF00);
		EntityRegistry.registerGlobalEntityID(EntityFBI.class, "entity_ntm_fbi", EntityRegistry.findGlobalUniqueEntityId(), 0x008000, 0x404040);
		EntityRegistry.registerGlobalEntityID(EntityRADBeast.class, "entity_ntm_radiation_blaze", EntityRegistry.findGlobalUniqueEntityId(), 0x303030, 0x008000);
	}
	
	public static void Initialization() {
		
	}
	
	public static void postInitialization() {
		
	}
}
